#!/usr/bin/env python
import argparse, signal
from libmproxy import proxy, dump, utils

if __name__ == '__main__':
    utils.check_netlib_version_equality()
    parser = argparse.ArgumentParser(usage = "%(prog)s [options] [filter]")
    dump.DumpMaster.add_arguments(parser)

    options = parser.parse_args()
    server = proxy.get_server(options)

    m = dump.DumpMaster(server, options)
    def cleankill(*args, **kwargs):
        m.shutdown()
    signal.signal(signal.SIGTERM, cleankill)
    try:
        m.run()
    except KeyboardInterrupt:
        pass
